
package com.adobe.idp.services.getpdf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ModulisticaOnline_GetPDF", targetNamespace = "http://adobe.com/idp/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModulisticaOnlineGetPDF {


    /**
     * 
     * @param outDocumentForm
     * @param inStringHash
     * @param inIntIdAttachment
     * @param outDocumentPdf
     */
    @WebMethod(action = "invoke..11.0.0")
    @RequestWrapper(localName = "invoke", targetNamespace = "http://adobe.com/idp/services", className = "com.adobe.idp.services.getpdf.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://adobe.com/idp/services", className = "com.adobe.idp.services.getpdf.InvokeResponse")
    public void invoke(
        @WebParam(name = "in_int_idAttachment", targetNamespace = "http://adobe.com/idp/services")
        Integer inIntIdAttachment,
        @WebParam(name = "in_string_hash", targetNamespace = "http://adobe.com/idp/services")
        String inStringHash,
        @WebParam(name = "out_document_form", targetNamespace = "http://adobe.com/idp/services", mode = WebParam.Mode.OUT)
        Holder<BLOB> outDocumentForm,
        @WebParam(name = "out_document_pdf", targetNamespace = "http://adobe.com/idp/services", mode = WebParam.Mode.OUT)
        Holder<BLOB> outDocumentPdf);

}
