//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 03:10:18 PM CEST 
//


package it.smartcampuslab.p3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dichiarazione" type="{http://schemas.sygest.it/}type_dichiarazione_proloco"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dichiarazione"
})
@XmlRootElement(name = "dichiarazioni")
public class Dichiarazioni {

    @XmlElement(required = true)
    protected TypeDichiarazioneProloco dichiarazione;

    /**
     * Gets the value of the dichiarazione property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDichiarazioneProloco }
     *     
     */
    public TypeDichiarazioneProloco getDichiarazione() {
        return dichiarazione;
    }

    /**
     * Sets the value of the dichiarazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDichiarazioneProloco }
     *     
     */
    public void setDichiarazione(TypeDichiarazioneProloco value) {
        this.dichiarazione = value;
    }

}
