//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 03:02:26 PM CEST 
//


package it.smartcampuslab.p3;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.smartcampuslab.p3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.smartcampuslab.p3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco }
     * 
     */
    public TypeDichiarazioneProloco createTypeDichiarazioneProloco() {
        return new TypeDichiarazioneProloco();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio createTypeDichiarazioneProlocoStampaSchedaPunteggio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomanda() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggi() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotale() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotalePUNTEGGIO }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotalePUNTEGGIO createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotalePUNTEGGIO() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotalePUNTEGGIO();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleL }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleL createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotaleL() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleL();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleF }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleF createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotaleF() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleF();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleE }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleE createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotaleE() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleE();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioL() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLb }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLb createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioLPunteggioLb() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLb();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLa1 }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLa1 createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioLPunteggioLa1() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLa1();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioF() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFe }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFe createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFe() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFe();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFd }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFd createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFd() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFd();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFc }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFc createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFc() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFc();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFb }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFb createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFb() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFb();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFa }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFa createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFa() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFa();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioF1 }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioF1 createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioF1() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioF1();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioE }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioE createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioE() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioE();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Domanda }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Domanda createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaDomanda() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Domanda();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.NucleoFamiliare }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.NucleoFamiliare createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioNucleoFamiliare() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.NucleoFamiliare();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioStoriaDomanda() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda.Domanda }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda.Domanda createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioStoriaDomandaDomanda() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda.Domanda();
    }

    /**
     * Create an instance of {@link Dichiarazioni }
     * 
     */
    public Dichiarazioni createDichiarazioni() {
        return new Dichiarazioni();
    }

    /**
     * Create an instance of {@link TypeStruttura }
     * 
     */
    public TypeStruttura createTypeStruttura() {
        return new TypeStruttura();
    }

    /**
     * Create an instance of {@link TypeComponente }
     * 
     */
    public TypeComponente createTypeComponente() {
        return new TypeComponente();
    }

    /**
     * Create an instance of {@link TypeAutocertificazione }
     * 
     */
    public TypeAutocertificazione createTypeAutocertificazione() {
        return new TypeAutocertificazione();
    }

    /**
     * Create an instance of {@link TypeRecapito }
     * 
     */
    public TypeRecapito createTypeRecapito() {
        return new TypeRecapito();
    }

    /**
     * Create an instance of {@link TypePeriodoResidenza }
     * 
     */
    public TypePeriodoResidenza createTypePeriodoResidenza() {
        return new TypePeriodoResidenza();
    }

    /**
     * Create an instance of {@link TypeEsenzionemarcabollo }
     * 
     */
    public TypeEsenzionemarcabollo createTypeEsenzionemarcabollo() {
        return new TypeEsenzionemarcabollo();
    }

    /**
     * Create an instance of {@link TypeMarcabollo }
     * 
     */
    public TypeMarcabollo createTypeMarcabollo() {
        return new TypeMarcabollo();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotalePUNTEGGIO.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotalePUNTEGGIO.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotalePUNTEGGIODettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotalePUNTEGGIO.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleL.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleL.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotaleLDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleL.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleF.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleF.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotaleFDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleF.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleE.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleE.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioTotaleTotaleEDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioTotale.TotaleE.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLb.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLb.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioLPunteggioLbDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLb.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLa1 .Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLa1 .Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioLPunteggioLa1Dettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioL.PunteggioLa1 .Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFe.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFe.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFeDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFe.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFd.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFd.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFdDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFd.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFc.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFc.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFcDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFc.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFb.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFb.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFbDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFb.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFa.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFa.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioFaDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioFa.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioF1 .Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioF1 .Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioFPunteggioF1Dettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioF.PunteggioF1 .Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioE.Dettaglio }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioE.Dettaglio createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaPunteggiPunteggioEDettaglio() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Punteggi.PunteggioE.Dettaglio();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Domanda.Richiedente }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Domanda.Richiedente createTypeDichiarazioneProlocoStampaSchedaPunteggioDatiPunteggiDomandaDomandaRichiedente() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.DatiPunteggiDomanda.Domanda.Richiedente();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.Ente }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.Ente createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioEnte() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.Ente();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.DatiIdentificativiDomanda }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.DatiIdentificativiDomanda createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioDatiIdentificativiDomanda() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.DatiIdentificativiDomanda();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.CondizioneFamiliare }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.CondizioneFamiliare createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioCondizioneFamiliare() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.CondizioneFamiliare();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.IndicatoriEconomici }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.IndicatoriEconomici createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioIndicatoriEconomici() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.IndicatoriEconomici();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.DatiAlloggioOccupato }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.DatiAlloggioOccupato createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioDatiAlloggioOccupato() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.DatiAlloggioOccupato();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.NucleoFamiliare.ComponenteNucleoFamiliare }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.NucleoFamiliare.ComponenteNucleoFamiliare createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioNucleoFamiliareComponenteNucleoFamiliare() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.NucleoFamiliare.ComponenteNucleoFamiliare();
    }

    /**
     * Create an instance of {@link TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda.Domanda.Richiedente }
     * 
     */
    public TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda.Domanda.Richiedente createTypeDichiarazioneProlocoStampaSchedaPunteggioAssegnazioneAlloggioStoriaDomandaDomandaRichiedente() {
        return new TypeDichiarazioneProloco.StampaSchedaPunteggio.AssegnazioneAlloggio.StoriaDomanda.Domanda.Richiedente();
    }

}
