//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 03:02:26 PM CEST 
//


package it.smartcampuslab.p3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for type_autocertificazione complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="type_autocertificazione">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="componente_maggior_residenza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="periodi_residenza" type="{http://schemas.sygest.it/}type_periodo_residenza" maxOccurs="unbounded"/>
 *         &lt;element name="totale_anni" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totale_mesi" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="iscritto_AIRE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AIRE_anni" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AIRE_mesi" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AIRE_comuni" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="data_consensuale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tribunale_consensuale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="data_giudiziale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tribunale_giudiziale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="data_temporaneo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tribunale_temporaneo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="componenti" type="{http://schemas.sygest.it/}type_componente" maxOccurs="unbounded"/>
 *         &lt;element name="recapito" type="{http://schemas.sygest.it/}type_recapito"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type_autocertificazione", propOrder = {
    "componenteMaggiorResidenza",
    "periodiResidenza",
    "totaleAnni",
    "totaleMesi",
    "iscrittoAIRE",
    "aireAnni",
    "aireMesi",
    "aireComuni",
    "dataConsensuale",
    "tribunaleConsensuale",
    "dataGiudiziale",
    "tribunaleGiudiziale",
    "dataTemporaneo",
    "tribunaleTemporaneo",
    "componenti",
    "recapito"
})
public class TypeAutocertificazione {

    @XmlElement(name = "componente_maggior_residenza", required = true)
    protected String componenteMaggiorResidenza;
    @XmlElement(name = "periodi_residenza", required = true)
    protected List<TypePeriodoResidenza> periodiResidenza;
    @XmlElement(name = "totale_anni")
    protected int totaleAnni;
    @XmlElement(name = "totale_mesi")
    protected int totaleMesi;
    @XmlElement(name = "iscritto_AIRE", required = true)
    protected String iscrittoAIRE;
    @XmlElement(name = "AIRE_anni")
    protected int aireAnni;
    @XmlElement(name = "AIRE_mesi")
    protected int aireMesi;
    @XmlElement(name = "AIRE_comuni", required = true)
    protected String aireComuni;
    @XmlElement(name = "data_consensuale", required = true)
    protected String dataConsensuale;
    @XmlElement(name = "tribunale_consensuale", required = true)
    protected String tribunaleConsensuale;
    @XmlElement(name = "data_giudiziale", required = true)
    protected String dataGiudiziale;
    @XmlElement(name = "tribunale_giudiziale", required = true)
    protected String tribunaleGiudiziale;
    @XmlElement(name = "data_temporaneo", required = true)
    protected String dataTemporaneo;
    @XmlElement(name = "tribunale_temporaneo", required = true)
    protected String tribunaleTemporaneo;
    @XmlElement(required = true)
    protected List<TypeComponente> componenti;
    @XmlElement(required = true)
    protected TypeRecapito recapito;

    /**
     * Gets the value of the componenteMaggiorResidenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponenteMaggiorResidenza() {
        return componenteMaggiorResidenza;
    }

    /**
     * Sets the value of the componenteMaggiorResidenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponenteMaggiorResidenza(String value) {
        this.componenteMaggiorResidenza = value;
    }

    /**
     * Gets the value of the periodiResidenza property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodiResidenza property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodiResidenza().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypePeriodoResidenza }
     * 
     * 
     */
    public List<TypePeriodoResidenza> getPeriodiResidenza() {
        if (periodiResidenza == null) {
            periodiResidenza = new ArrayList<TypePeriodoResidenza>();
        }
        return this.periodiResidenza;
    }

    /**
     * Gets the value of the totaleAnni property.
     * 
     */
    public int getTotaleAnni() {
        return totaleAnni;
    }

    /**
     * Sets the value of the totaleAnni property.
     * 
     */
    public void setTotaleAnni(int value) {
        this.totaleAnni = value;
    }

    /**
     * Gets the value of the totaleMesi property.
     * 
     */
    public int getTotaleMesi() {
        return totaleMesi;
    }

    /**
     * Sets the value of the totaleMesi property.
     * 
     */
    public void setTotaleMesi(int value) {
        this.totaleMesi = value;
    }

    /**
     * Gets the value of the iscrittoAIRE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIscrittoAIRE() {
        return iscrittoAIRE;
    }

    /**
     * Sets the value of the iscrittoAIRE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIscrittoAIRE(String value) {
        this.iscrittoAIRE = value;
    }

    /**
     * Gets the value of the aireAnni property.
     * 
     */
    public int getAIREAnni() {
        return aireAnni;
    }

    /**
     * Sets the value of the aireAnni property.
     * 
     */
    public void setAIREAnni(int value) {
        this.aireAnni = value;
    }

    /**
     * Gets the value of the aireMesi property.
     * 
     */
    public int getAIREMesi() {
        return aireMesi;
    }

    /**
     * Sets the value of the aireMesi property.
     * 
     */
    public void setAIREMesi(int value) {
        this.aireMesi = value;
    }

    /**
     * Gets the value of the aireComuni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIREComuni() {
        return aireComuni;
    }

    /**
     * Sets the value of the aireComuni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIREComuni(String value) {
        this.aireComuni = value;
    }

    /**
     * Gets the value of the dataConsensuale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataConsensuale() {
        return dataConsensuale;
    }

    /**
     * Sets the value of the dataConsensuale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataConsensuale(String value) {
        this.dataConsensuale = value;
    }

    /**
     * Gets the value of the tribunaleConsensuale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTribunaleConsensuale() {
        return tribunaleConsensuale;
    }

    /**
     * Sets the value of the tribunaleConsensuale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTribunaleConsensuale(String value) {
        this.tribunaleConsensuale = value;
    }

    /**
     * Gets the value of the dataGiudiziale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataGiudiziale() {
        return dataGiudiziale;
    }

    /**
     * Sets the value of the dataGiudiziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataGiudiziale(String value) {
        this.dataGiudiziale = value;
    }

    /**
     * Gets the value of the tribunaleGiudiziale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTribunaleGiudiziale() {
        return tribunaleGiudiziale;
    }

    /**
     * Sets the value of the tribunaleGiudiziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTribunaleGiudiziale(String value) {
        this.tribunaleGiudiziale = value;
    }

    /**
     * Gets the value of the dataTemporaneo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataTemporaneo() {
        return dataTemporaneo;
    }

    /**
     * Sets the value of the dataTemporaneo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataTemporaneo(String value) {
        this.dataTemporaneo = value;
    }

    /**
     * Gets the value of the tribunaleTemporaneo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTribunaleTemporaneo() {
        return tribunaleTemporaneo;
    }

    /**
     * Sets the value of the tribunaleTemporaneo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTribunaleTemporaneo(String value) {
        this.tribunaleTemporaneo = value;
    }

    /**
     * Gets the value of the componenti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componenti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponenti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeComponente }
     * 
     * 
     */
    public List<TypeComponente> getComponenti() {
        if (componenti == null) {
            componenti = new ArrayList<TypeComponente>();
        }
        return this.componenti;
    }

    /**
     * Gets the value of the recapito property.
     * 
     * @return
     *     possible object is
     *     {@link TypeRecapito }
     *     
     */
    public TypeRecapito getRecapito() {
        return recapito;
    }

    /**
     * Sets the value of the recapito property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeRecapito }
     *     
     */
    public void setRecapito(TypeRecapito value) {
        this.recapito = value;
    }

}
