//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 11:38:55 AM CEST 
//


package it.smartcampuslab.p3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for type_marcabollo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="type_marcabollo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="giorno_emissione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ora_emissione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="identificativo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type_marcabollo", propOrder = {
    "giornoEmissione",
    "oraEmissione",
    "identificativo"
})
public class TypeMarcabollo {

    @XmlElement(name = "giorno_emissione", required = true)
    protected String giornoEmissione;
    @XmlElement(name = "ora_emissione", required = true)
    protected String oraEmissione;
    @XmlElement(required = true)
    protected String identificativo;

    /**
     * Gets the value of the giornoEmissione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiornoEmissione() {
        return giornoEmissione;
    }

    /**
     * Sets the value of the giornoEmissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiornoEmissione(String value) {
        this.giornoEmissione = value;
    }

    /**
     * Gets the value of the oraEmissione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOraEmissione() {
        return oraEmissione;
    }

    /**
     * Sets the value of the oraEmissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOraEmissione(String value) {
        this.oraEmissione = value;
    }

    /**
     * Gets the value of the identificativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativo() {
        return identificativo;
    }

    /**
     * Sets the value of the identificativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativo(String value) {
        this.identificativo = value;
    }

}
