
package com.adobe.idp.services.formupload;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ModulisticaOnline_FormUpload", targetNamespace = "http://adobe.com/idp/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModulisticaOnlineFormUpload {


    /**
     * 
     * @param xmlToken
     * @param inStringFormid
     * @param outXmlResult
     * @param outQ
     * @param xmlDoc
     */
    @WebMethod(action = "invoke..11.0.0")
    @RequestWrapper(localName = "invoke", targetNamespace = "http://adobe.com/idp/services", className = "com.adobe.idp.services.formupload.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://adobe.com/idp/services", className = "com.adobe.idp.services.formupload.InvokeResponse")
    public void invoke(
        @WebParam(name = "in_string_formid", targetNamespace = "http://adobe.com/idp/services")
        String inStringFormid,
        @WebParam(name = "xml_doc", targetNamespace = "http://adobe.com/idp/services")
        XML xmlDoc,
        @WebParam(name = "xml_token", targetNamespace = "http://adobe.com/idp/services")
        XML xmlToken,
        @WebParam(name = "out_q", targetNamespace = "http://adobe.com/idp/services", mode = WebParam.Mode.OUT)
        Holder<XML> outQ,
        @WebParam(name = "out_xml_result", targetNamespace = "http://adobe.com/idp/services", mode = WebParam.Mode.OUT)
        Holder<XML> outXmlResult);

}
