
package it.infotn.epu;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DomandaEPUService", targetNamespace = "http://epu.infotn.it", wsdlLocation = "https://ws-p.servizi.infotn.it/epu/DomandaEPUService?wsdl")
public class DomandaEPUService
    extends Service
{

//    private final static URL DOMANDAEPUSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.infotn.epu.DomandaEPUService.class.getName());

//    static {
//        URL url = null;
//        try {
//            URL baseUrl;
//            baseUrl = it.infotn.epu.DomandaEPUService.class.getResource(".");
//            url = new URL(baseUrl, "file:/C:/workspace-GIT/service.epu.web/src/main/resources/DomandaEPUService.wsdl");
//        } catch (MalformedURLException e) {
//            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace-GIT/service.epu.web/src/main/resources/DomandaEPUService.wsdl', retrying as a local file");
//            logger.warning(e.getMessage());
//        }
//        DOMANDAEPUSERVICE_WSDL_LOCATION = url;
//    }

    public DomandaEPUService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomandaEPUService() {
//        super(DOMANDAEPUSERVICE_WSDL_LOCATION, new QName("http://epu.infotn.it", "DomandaEPUService"));
    	super(Thread.currentThread().getContextClassLoader().getResource("/DomandaEPUService.wsdl"), new QName("http://epu.infotn.it", "DomandaEPUService"));
    }

    /**
     * 
     * @return
     *     returns DomandaEPU
     */
    @WebEndpoint(name = "DomandaEPUPort")
    public DomandaEPU getDomandaEPUPort() {
        return super.getPort(new QName("http://epu.infotn.it", "DomandaEPUPort"), DomandaEPU.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomandaEPU
     */
    @WebEndpoint(name = "DomandaEPUPort")
    public DomandaEPU getDomandaEPUPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://epu.infotn.it", "DomandaEPUPort"), DomandaEPU.class, features);
    }

}
