
package it.infotn.epu;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DomandaEpuFault", targetNamespace = "http://epu.infotn.it")
public class DomandaEpuFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DomandaEpuFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DomandaEpuFault_Exception(String message, DomandaEpuFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DomandaEpuFault_Exception(String message, DomandaEpuFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.infotn.epu.DomandaEpuFault
     */
    public DomandaEpuFault getFaultInfo() {
        return faultInfo;
    }

}
