
package com.adobe.idp.services.approvalpdf;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ModulisticaOnline_ApprovalPDFService", targetNamespace = "http://adobe.com/idp/services", wsdlLocation = "https://ws-t.servizi.infotn.it/soap/services/ModulisticaOnline/ApprovalPDF?wsdl")
public class ModulisticaOnlineApprovalPDFService
    extends Service
{

//    private final static URL MODULISTICAONLINEAPPROVALPDFSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.adobe.idp.services.approvalpdf.ModulisticaOnlineApprovalPDFService.class.getName());

//    static {
//        URL url = null;
//        try {
//            URL baseUrl;
//            baseUrl = com.adobe.idp.services.approvalpdf.ModulisticaOnlineApprovalPDFService.class.getResource(".");
//            url = new URL(baseUrl, "http://172.20.1.141:8080/soap/services/ModulisticaOnline/ApprovalPDF");
//        } catch (MalformedURLException e) {
//            logger.warning("Failed to create URL for the wsdl Location: 'http://172.20.1.141:8080/soap/services/ModulisticaOnline/ApprovalPDF', retrying as a local file");
//            logger.warning(e.getMessage());
//        }
//        MODULISTICAONLINEAPPROVALPDFSERVICE_WSDL_LOCATION = url;
//    }

    public ModulisticaOnlineApprovalPDFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModulisticaOnlineApprovalPDFService() throws MalformedURLException {
//        super(MODULISTICAONLINEAPPROVALPDFSERVICE_WSDL_LOCATION, new QName("http://adobe.com/idp/services", "ModulisticaOnline_ApprovalPDFService"));
//    	super(new URL("https://ws-t.servizi.infotn.it/soap/services/ModulisticaOnline/ApprovalPDF?wsdl"), new QName("http://adobe.com/idp/services", "ModulisticaOnline_ApprovalPDFService"));
    	super(Thread.currentThread().getContextClassLoader().getResource("/ApprovalPDF.wsdl"), new QName("http://adobe.com/idp/services", "ModulisticaOnline_ApprovalPDFService"));
    }

    /**
     * 
     * @return
     *     returns ModulisticaOnlineApprovalPDF
     */
    @WebEndpoint(name = "ApprovalPDF")
    public ModulisticaOnlineApprovalPDF getApprovalPDF() {
        return super.getPort(new QName("http://adobe.com/idp/services", "ApprovalPDF"), ModulisticaOnlineApprovalPDF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModulisticaOnlineApprovalPDF
     */
    @WebEndpoint(name = "ApprovalPDF")
    public ModulisticaOnlineApprovalPDF getApprovalPDF(WebServiceFeature... features) {
        return super.getPort(new QName("http://adobe.com/idp/services", "ApprovalPDF"), ModulisticaOnlineApprovalPDF.class, features);
        

    }

}
